LPS 125507
liferay-data-engine/liferay-portal pull request #105
Opened 2021-01-05 22:06 UTC by rodrigopaulino

- LPS-125477 Modify macro to add fragment above another one
- LPS-125477 Add locator for preview button on management bar
- LPS-125477 Add macro to edit Collection Category Filter
- LPS-125477 Add locator for Collection Category Filter dropdown toggle
- LPS-125477 Add macro to select filter in Collection Category Filter
- LPS-125477 Modify macros to add site member view permission when blogs entry and document created
- LPS-125477 Add if to make it reusable
- LPS-125477 Add case to assert filter results of collection page based on manual collection by single category
- LPS-125415 Separator fields do not have values to update
- LPS-123817 Create fields to be able to configure proxy for ElasticSearch client.
- LPS-123817 Use configuration proxy settings if enabled, if not try, as fallback, if enabled, system settings property to be able to connect using proxy.
- LPS-123817 Add language keys to new configuration fields.
- LPS-123817 buildLang
- LPS-123817 Semantic Versioning.
- LPS-123817 portal-search-elasticsearch7-impl: Initial test for ProxyConfigBuilder
- LPS-125091 Adds new API module for item selector classes
- LPS-125091 Adds new item selector criterion for DDM User Personal Folder
- LPS-125091 Uses new item selector criterion, to allow users select documents from theirs personal folder
- LPS-125091 Adds groupId and folderId to Criterion
- LPS-125091 No needed since we are setting it on the criterion
- LPS-125091 Implements Criterion Handler
- LPS-125091 Implements necessary classes to upload file entries to the user personal folder, copy from DLUploadResponseHandler and DLUploadFileEntryHandler to keep the same behaviour, no logic changes
- LPS-125091 Implements new action command to upload file entries to user personal folder
- LPS-125091 Implements user personal folder item selector view
- LPS-125091 Copy logic from journal_images.jsp and JournalArticleImpl
- LPS-125091 packageinfo
- LPS-125091 build.gradle
- LPS-125091 Language keys
- LPS-125091 buildLang
- LPS-125091 Removes folderId assertion since it is not necessary, we are using the criterion to set the folder id instead of passing it through URL
- LPS-125091 Adds criterion to the mock
- LPS-125091 Removes ddm prefix for jsp files
- LPS-123431 Avoid showing 0 when there are no image sizes
- LPS-123431 Add tests for ImageSelectorSize
- LPS-123431 Add tests for ImageSelectorDescription
- LPS-123431 Add tests for useBackgroundImageQueries
- LPS-125090 Make MainServlet logic match PortalImpl logic
- LPS-125090 Add log message
- LPS-125169 Inlines Liferay.Language.available calculation
- LPS-125168 Simplify minification of handcrafted JS
- LPS-125168 Simplify minification of handcrafted Bundle Config JS
- LPS-125168 Adds module to JS build pipeline
- LPS-125168 Avoids unnecessary servlet request to retrieve Loader configuration
- LPS-125169 Serves loader from proper OSGi module
- LPS-125169 General SF. Removes unrelated leftovers
- LPS-125169 Avoids unnecessary servlet request to retrieve AUI bundle configuration
- LPS-125169 Removes lang APIs that return invalid paths
- LPS-125090 Our usual Java based standard.. don't minify too much
- LPS-84864 Regen
- LPS-84864 Extract common
- LPS-84864 Extract common
- LPS-84864 New copy impl to allow copy resource permission
- LPS-84864 New copy impl to allow copy resource permission
- LPS-84864 reword
- LPS-84864 Simplify and avoid using deprecated method
- LPS-84864 reword
- LPS-84864 as used
- LPS-84864 match other existing usage
- LPS-125128 create a util class into api module in order to expose method
- LPS-125128 move test class to api module
- LPS-125128 update references
- LPS-125128 use data definition from request to get ddmForm when data layout has no id
- LPS-125128 use data layout coming from request when dataDefinitionId and dataLayoutId do not exist
- LPS-125128 get definition from dataLayout when it has no id
- LPS-125128 update gradle dependencies
- LPS-125128 export util package
- LPS-125128 baseline
- LPS-125507 Avoid numeric fields being set to null

2021-01-05 22:06 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-01-05 22:08 UTC, rodrigopaulino commented
ci:test:sf

2021-01-05 22:08 UTC, rodrigopaulino commented
ci:test:relevant

2021-01-05 22:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/2474/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com//userContent/jobs/test-portal-source-format/builds/2474/jenkins-report.html">here</a>.</b></p>

2021-01-05 22:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1009de67c76e6aea7012e91270fbeb3da51087ed">1009de67c76e6aea7012e91270fbeb3da51087ed</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rodrigopaulino/liferay-portal/tree/LPS-125507">LPS-125507</a><br/>Branch GIT ID: <a href="https://github.com/rodrigopaulino/liferay-portal/commit/1353aef6a1e6b5b7384e01c4fc75171f967e55a7">1353aef6a1e6b5b7384e01c4fc75171f967e55a7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/2474/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/2474/jenkins-report.html">here</a>.</h5></details></html>

2021-01-05 22:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/3719/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3719/jenkins-report.html">here</a>.</b></p>

2021-01-05 22:15 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-15.liferay.com/job/test-portal-source-format/2474/">test-portal-source-format#2474</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/2474/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-data-engine/liferay-portal/pull/105">liferay-data-engine#105</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/76379.aspx">master - rodrigopaulino > liferay-data-engine - PR#105 - 2021-01-05[14:08:31]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/publish-spira-report/10405/">publish-spira-report#10405</a><br />

2021-01-06 00:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 9 out of 9 jobs passed</h3><h3>:x: ci:test:relevant - 23 out of 25 jobs passed in 2 hours 17 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1009de67c76e6aea7012e91270fbeb3da51087ed">1009de67c76e6aea7012e91270fbeb3da51087ed</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/15218ef33680a1fe233ea812e8d097cfcb0feb42">15218ef33680a1fe233ea812e8d097cfcb0feb42</a></p><details><summary><strong>ci:test:stable - 9 out of 9 jobs PASSED</strong></summary><details><summary><strong>9 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372796/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448897/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/400515/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461300/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/212802/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/483016/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372799/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/212801/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448895/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 23 out of 25 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/3719/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/421917/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460521/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448896/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372796/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372800/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/212803/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461301/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448897/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/400515/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/324766/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460519/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/421916/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450584/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461300/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372798/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460520/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/212802/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372797/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/483016/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372799/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450425/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/212801/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372795/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448895/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3719/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-8.liferay.com/job/test-por [...]

2021-01-06 01:05 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/3719/">test-portal-acceptance-pullrequest(master)#3719</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3719/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-data-engine/liferay-portal/pull/105">liferay-data-engine#105</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/76409.aspx">master - rodrigopaulino > liferay-data-engine - PR#105 - 2021-01-05[14:11:58]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-16.liferay.com/job/publish-spira-report/13580/">publish-spira-report#13580</a><br />

2021-01-06 15:22 UTC, rodrigopaulino commented
These unique failures seem unrelated to the changes in this PR.

2021-01-07 11:52 UTC, jeyvison requested changes

2021-01-07 13:57 UTC, rodrigopaulino commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/src/main/java/com/liferay/dynamic/data/mapping/form/renderer/internal/DDMFormFieldTemplateContextFactory.java
> +					!StringUtil.equals(ddmFormField.getType(), "numeric")) {
You got it

2021-01-07 14:10 UTC, closed without merging

2021-01-07 14:12 UTC, rodrigopaulino commented
@jeyvison https://github.com/liferay-data-engine/liferay-portal/pull/112